#Versione italiana del config
#Per usare, rinomina config-it in config.
#(Versione del config richiesta dal cliente)

#Allows users to give reputation of offline players
#From spigotmc's documentation: "This method may involve a blocking web request to get the UUID for the given name."
#Meaning: This may lag out your server if abused.
allowOfflineReputation: true
offlinePlayerFeedback: "Il giocatore non è online."
tooManyArgsError: "Syntax: /rep [who]"
add1Feedback: "&aHai dato +1 reputazione a questo giocatore."
remove1Feedback: "&cHai rimosso 1 reputazione da questo giocatore."
selfFeedback: "&cNon puoi modificare la tua stessa reputazione."
receiveFeedback: true
receivePositiveFeedback: "&aHai guadagnato &21 punto reputazione!"
followerFeedback: " &7[&l&4?&7]"
receiveNegativeFeedback: "&cHai perso un &41 punto reputazione!"
gui:
  title: "&l&7[&cRep&l&dGui&l&7]"
  repLore: "Reputazione: %reputation%"
  remove1:
    material: RED_WOOL
    name: "&4-1"
    lore:
      - "&7Clicca per &ctogliere&7 1 reputazione"
  add1:
    material: GREEN_WOOL
    name: "&a+1"
    lore:
      - "&7Clicca per &atogliere&7 1 reputazione"
